#pragma once

#define MASTER_LEFT

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY

#define DEBOUNCE 5

#define MOUSEKEY_WHEEL_INTERVAL 75
#define MOUSEKEY_WHEEL_DELAY 100
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0
#define MOUSEKEY_WHEEL_MAX_SPEED 10


